#!/bin/bash

source ../../common_scripts.sh

clean_up

branch "master"
commit "1"
commit "2"
commit "3"

branch "branch-1"
commit "4"
commit "5"
commit "6"

branch "master"
commit "7"

cat INSTRUCTIONS.md
