#!/bin/bash

source ../../common_scripts.sh

clean_up

branch "master"
commit "1"
commit "2"

branch "branch-1"
commit "3"

branch "branch-2"
commit "4"

branch "branch-3"
commit "5"

branch "branch-2"
commit "6"

branch "branch-1"
commit "7"

cat INSTRUCTIONS.md
